x=eval(input("enetr the value:"))
y=eval(input("enter the value:"))
z=eval(input("enter the value:"))
a=eval(input("enter the value:"))
b=eval(input("enetr the value:"))
c=eval(input("enter the value :"))
d=eval(input("eneter the value:"))
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(x))
print(type(z))
print(type(y))
